name: jersey-mapping

on:
  # Manual trigger (on-demand)
  workflow_dispatch:
  repository_dispatch:
    types: [jersey]
  schedule:
    # Runs based on the configured schedule
    - cron: '0 9 1,15 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  call-mapping-workflow:
    uses: abeyta-labs/saa-workflows/.github/workflows/build-mapping.yml@main
    with:
      mapping-name: jersey
      repo-url: https://github.com/eclipse-ee4j/jersey
      coordinates: org.glassfish.jersey.ext:jersey-spring5
    secrets: inherit
